package com.example.shan_inventory.data

import com.google.firebase.database.IgnoreExtraProperties

/**
 * Data class representing a Part in the inventory system
 * Contains all the information needed to track and manage inventory parts
 * 
 * @property id Unique identifier for the part (generated by Firebase)
 * @property partName Name of the part (required field)
 * @property quantity Number of parts available in inventory
 * @property cabinetName Cabinet number where the part is stored
 * @property shelfRow Row number within the cabinet
 * @property shelfColumn Column number within the cabinet
 * @property remarks Additional notes or comments about the part
 * @property imageUrl Single image URL (kept for backward compatibility with older data)
 * @property imageUrls List of image URLs for multiple images (up to 5 images supported)
 * @property createdAt Timestamp when the part was first created
 */
@IgnoreExtraProperties
data class Part(
    val id: String = "",
    val partName: String = "",
    val quantity: Int = 0,
    val cabinetName: String = "",
    val shelfRow: String = "",
    val shelfColumn: String = "",
    val remarks: String = "",
    val imageUrl: String = "", // Keep for backward compatibility
    val imageUrls: List<String> = emptyList(), // New field for multiple images
    val createdAt: Long = System.currentTimeMillis()
)

